[package]
name = "middlesock"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json", "blocking"] }
figment = { version = "0.10" }

[dependencies.rocket]
version = "0.5.0-rc.3"
features = ["json"]
